{
 "title": "Gateway AI overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "eth", "label": "Eth price", "query": "2675" },
   { "name": "model", "label": "Model", "query": { "query": "label_values(model_name)" } },
   { "name": "job_livepeer", "label": "Job filter: Gateway" },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(orchestrator_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview from ${__from:date:YYYY/MM/DD HH:mm} to ${__to:date:YYYY/MM/DD HH:mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 }, "options": { "content": "_____\n# Tickets\n_____" } },
  { "type": "text", "gridPos": { "h": 3, "w": 18, "x": 6, "y": 1 }, "options": { "content": "_____\n# Model stats\n_____" } },
  {
   "title": "Ticket value sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[$__range])) / 1e+09 * $eth",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "💵 Daily/Monthly Fees",
   "type": "timeseries",
   "description": "Based on the moving average with an interval of 24 hours",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(rate(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[1d])*(60*60*24*365)/12)*1e-9 * $eth or on() vector(0)",
     "legendFormat": "Monthly"
    },
    {
     "expr": "(rate(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[1d])*(60*60*24))*1e-9 * $eth or on() vector(0)",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "Requests completed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\"}[$__interval]))",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 }, "options": { "content": "_____\n# Worker stats\n_____" } },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "piechart",
   "description": "Where did the error which caused the job to fail occur?",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (orchestrator_address) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  {
   "title": "Average cost",
   "type": "table",
   "description": "An estimation per pipeline:\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\"} * 1 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "table",
   "description": "An estimation per pipeline:\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate 25 frames of 1024x1024 \n- img2vid: time to generate 25 frames of 1024x1024\n- audio2txt: time to process a minute of audio",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\"} * 1)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Subsection: Model specific stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "_____\n# Selected model: ${model} \n_____"
   }
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\", model_name=\"$model\"}[$__range]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", model_name=\"$model\"}[$__range]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "timeseries",
   "description": "An estimation per pipeline:\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate 25 frames of 1024x1024 \n- img2vid: time to generate 25 frames of 1024x1024\n- audio2txt: time to process a minute of audio",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", model_name=\"$model\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", model_name=\"$model\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", model_name=\"$model\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", model_name=\"$model\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", model_name=\"$model\"} * 1)",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  {
   "title": "Average price",
   "type": "table",
   "description": "An estimation per pipeline:\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", model_name=\"$model\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", model_name=\"$model\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", model_name=\"$model\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", model_name=\"$model\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", model_name=\"$model\"} * 1 * 1e-18 * $eth)",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (orchestrator_address, error_code) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", model_name=\"$model\"}[$__range]))",
     "legendFormat": "{{orchestrator_address}} `{{error_code}}`"
    }
   ]
  },
  {
   "title": "Subsection: Worker specific stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "_____\n# Selected node: ${worker} \n_____"
   }
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name, error_code) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", orchestrator_address=\"$worker\"}[$__range]))",
     "legendFormat": "{{pipeline}}/{{model_name}}: `{{error_code}}`"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "timeseries",
   "description": "An estimation per pipeline:\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate 25 frames of 1024x1024 \n- img2vid: time to generate 25 frames of 1024x1024\n- audio2txt: time to process a minute of audio",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", orchestrator_address=\"$worker\" } * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", orchestrator_address=\"$worker\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", orchestrator_address=\"$worker\"} * 1)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Average cost",
   "type": "table",
   "description": "An estimation per pipeline:\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", orchestrator_address=\"$worker\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}} {{orchestrator_address}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", orchestrator_address=\"$worker\"} * 1 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  }
 ]
}