{
 "title": "Orchestrator AI overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "eth", "label": "Eth price", "query": "2675" },
   { "name": "job_livepeer", "label": "Job filter: Orchestrator" },
   { "name": "job_gpu", "label": "Job filter: GPU" }
  ]
 },
 "panels": [
  {
   "title": "Overview from ${__from:date:YYYY/MM/DD HH:mm} to ${__to:date:YYYY/MM/DD HH:mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 }, "options": { "content": "_____\n# Tickets\n_____" } },
  { "type": "text", "gridPos": { "h": 3, "w": 18, "x": 6, "y": 1 }, "options": { "content": "_____\n# Model stats\n_____" } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_winning_tickets_recv{job=~\"^.*$job_livepeer.*$\"}[7d]))",
     "legendFormat": "Wins"
    },
    {
     "expr": "sum(increase(livepeer_ticket_value_recv{job=~\"^.*$job_livepeer.*$\"}[7d])) / 1e+09 * $eth",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(increase(livepeer_value_redeemed{job=~\"^.*$job_livepeer.*$\"}[7d])) / 1e+09 * $eth",
     "legendFormat": "Payed"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Average income",
   "type": "table",
   "description": "An estimation per pipeline:\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\"} * 1 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "💵 Daily/Monthly Fees",
   "type": "timeseries",
   "description": "Based on the moving average with an interval of 24 hours",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(rate(livepeer_ticket_value_recv{job=~\"^.*$job_livepeer.*$\"} [1d])*(60*60*24*365)/12)*1e-9 * $eth or on() vector(0)",
     "legendFormat": "Monthly"
    },
    {
     "expr": "(rate(livepeer_ticket_value_recv{job=~\"^.*$job_livepeer.*$\"}[1d])*(60*60*24))*1e-9 * $eth or on() vector(0)",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name, error_code) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\"}[$__range]))",
     "legendFormat": "{{pipeline}}/{{model_name}}: `{{error_code}}`"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 }, "options": { "content": "_____\n# Machine stats\n_____" } },
  {
   "title": "Requests completed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\"}[$__interval]))",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "utilization_gpu{job=~\"^.*$job_gpu.*$\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "VRAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_used{job=~\"^.*$job_gpu.*$\"}/memory_total{job=~\"^.*$job_gpu.*$\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "timeseries",
   "description": "An estimation per pipeline:\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate 25 frames of 1024x1024 \n- img2vid: time to generate 25 frames of 1024x1024\n- audio2txt: time to process a minute of audio",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\"} * 1024 * 1024 * 25)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\"} * 1)",
     "legendFormat": "{{pipeline}}/{{model_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature_gpu{job=~\"^.*$job_gpu.*$\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_versions{job=~\"^.*$job_livepeer.*$\"}",
     "legendFormat": "{{livepeerversion}}"
    }
   ]
  },
  {
   "title": "Subsection: GPU Memory and Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "temperature_gpu{job=~\"^.*$job_gpu.*$\"}",
       "legendFormat": "{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "memory_used{job=~\"^.*$job_gpu.*$\"}/memory_total{job=~\"^.*$job_gpu.*$\"}",
       "legendFormat": "{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Total Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "utilization_gpu{job=~\"^.*$job_gpu.*$\"}",
       "legendFormat": "{{gpu}}"
      }
     ]
    }
   ]
  }
 ]
}